- name: Enable redis 7
  ansible.builtin.shell: dnf module disable redis -y ; dnf module enable redis:7 -y
- name: Install redis
  ansible.builtin.dnf:
    name: redis
    state: latest
- name: replace config from local host to open
  ansible.builtin.replace:
    path:  /etc/redis/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'
- name: updated protected mode
  ansible.builtin.replace:
    path: /etc/redis/redis.conf
    regexp: 'protected-mode yes'
    replace: 'protected-mode no'
- name: Start redis
  ansible.builtin.systemd_service:
    name: redis
    state: restarted
    enabled: yes

