- name: copy mongo file
  ansible.builtin.copy:
    src: user.service
    dest: /etc/yum.repos.d/user.service
- name:  Install MongoDB
  ansible.builtin.dnf:
    name: mongodb-org
    state: latest
- name: replace config file from localhost to open
  ansible.builtin.replace:
    path:  /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'
- name: Start mongodb service
  ansible.builtin.systemd_service:
    name: mongod
    state: restarted
    enabled: yes

