- name: Add Application User
  ansible.builtin.user:
    name: roboshop
- name: remove old directory
  ansible.builtin.file:
    path: /app
    state: absent
- name: Create directory
  ansible.builtin.file:
    path: /app
    state: absent
- name: Download and extract the code
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/{{ component }}-v3.zip
    dest: /app
    remote_src: yes
